spring:
  application:
    name: CATALOG-MANAGEMENT-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/product_service
    username: root
    password: 2000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost